version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: tema-1-laborator
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - database-tema-1-laborator:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - db-tema-1-laborator

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: example
    networks:
      - db-tema-1-laborator

volumes:
  database-tema-1-laborator:
  
networks:
  db-tema-1-laborator:
    driver: bridge